POST http://localhost:8080/v1/watch-verifier/verify-watch
Content-Type: application/json

{
  "properties": [
    {
      "type": "CATEGORY",
      "value": "Comedy"
    }
  ],
  "videoId": "sxBliJuSXNI",
  "provider": "YOUTUBE",
  "mode": "WHITELIST"
}